version: "3.1"

services:
  aqua:
    image: ghcr.io/superioz/aqua:latest
    build: .
    env_file:
    - .env
    ports:
    - 8765:8765
    restart: always
    volumes:
    - ${PWD}/auth.yml:/etc/aqua/auth.yml
    - aqua:/var/lib/aqua

volumes:
  aqua:
