name: Release binaries
on:
  release:
    types: [created]
jobs:
  generate:
    name: Create release-artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
      - name: Build CLI for windows/amd64
        env:
          GOOS: windows
          GOARCH: amd64
        run: CGO_ENABLED=0 go build -o aq-cli-$GOOS-$GOARCH.exe ./cmd/aqcli/
      - name: Build CLI for linux/amd64
        env:
          GOOS: linux
          GOARCH: amd64
        run: CGO_ENABLED=0 go build -o aq-cli-$GOOS-$GOARCH ./cmd/aqcli/
      - name: Build server for windows/amd64
        env:
          GOOS: windows
          GOARCH: amd64
        run: CGO_ENABLED=0 go build -o aq-$GOOS-$GOARCH.exe ./cmd/aqua/
      - name: Build server for linux/amd64
        env:
          GOOS: linux
          GOARCH: amd64
        run: CGO_ENABLED=0 go build -o aq-$GOOS-$GOARCH ./cmd/aqua/
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'aq-*'
