on: [push]
name: Upload binaries to release
jobs:
  generate:
    name: Create release-artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
      - name: LS
        run: "ls -ahl"
#      - name: Generate the artifacts
#        uses: skx/github-action-build@master
#        with:
#          builder: .github/build
#      - name: Upload the artifacts
#        uses: skx/github-action-publish-binaries@master
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          args: 'aq-*'
